# Generated by Django 3.0.4 on 2020-03-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=25, null=True)),
                ('RollNumber', models.CharField(blank=True, max_length=25, null=True)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=200)),
                ('Date', models.DateField()),
            ],
        ),
    ]
